### ISSUE TITLE
验证码图片无法显示  Call to undefined function Think\imagettftext()

### ISSUE THREAD

**Issue by winer632** [stclair2201/GoOut-Panel#8]
可否帮忙看一下 http://120.76.118.128/cool/index.php?g=user&m=login&a=index

谢谢！

Call to undefined function Think\imagettftext()
错误位置
FILE: /usr/local/nginx/html/cool/simplewind/Core/Library/Think/Verify.class.php 　LINE: 166
ThinkCMF {Simple content manage Framework } -- [ WE CAN DO IT MORE SIMPLE ]

**Comment by stclair2201** [comment]
请参看 这个文档进行修改和调整。
http://thinkcmf.com/bug/bug/index/id/173.html

|
|

changjiang1988.hi@163.com
一起源于生熟 @incCon.H_Dan
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|
|

在 2016-05-28 14:23:19，"WangXinXin" notifications@github.com 写道：

可否帮忙看一下 http://120.76.118.128/cool/index.php?g=user&m=login&a=index

谢谢！

Call to undefined function Think\imagettftext()
错误位置
FILE: /usr/local/nginx/html/cool/simplewind/Core/Library/Think/Verify.class.php 　LINE: 166
ThinkCMF {Simple content manage Framework } -- [ WE CAN DO IT MORE SIMPLE ]

**Comment by winer632** [comment]
请问应该修改哪个文件呢？没有找到 public function verify() 这个函数，链接也没有提到文件名

**Comment by winer632** [comment]
重装了php，然后用phpinfo看到gd下面支持FreeType就对了
 gd GD Support => enabled 
GD Version => bundled (2.1.0 compatible) 
FreeType Support => enabled 
FreeType Linkage => with freetype 
FreeType Version => 2.4.0 
GIF Read Support => enabled 
GIF Create Support => enabled 
PNG Support => enabled 
libPNG Version => 1.5.13 
WBMP Support => enabled 
XBM Support => enabled 
JIS-mapped Japanese Font Support => enabled
Directive => Local Value => Master Value gd.jpeg_ignore_warning => 0 => 0
